version: '3'
services:
  redis-server:
    container_name: redis
    hostname: redis
    image: redis:latest
    # command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis-commander-server:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - REDIS_PASSWORD=123456
    depends_on:
      - redis-server
    links:
      - redis-server
    ports:
      - "6380:8081"